import turtle
pen=turtle.Turtle()
pen.color("yellow")
pen.speed(2)
pen.fillcolor("yellow")
pen.begin_fill()
for face in range(36):
    pen.forward(20)
    pen.right(10)
pen.end_fill()
pen.up()
pen.goto(-50,-50)
pen.down()
pen.color("black")
pen.fillcolor("black")
pen.begin_fill()
for eye1 in range(36):
    pen.forward(3)
    pen.right(10)
pen.end_fill()
pen.begin_fill()
pen.up()
pen.goto(50,-50)
pen.down()
for eye2 in range(36):
    pen.forward(3)
    pen.right(10)
pen.end_fill()
pen.up()
pen.goto(-50,-150)
pen.down()
pen.right(45)
for smile in range(10):
    pen.forward(15)
    pen.left(10)
turtle.done()